# The directory containing the source files to parse recursively
source: ./

# The types that aigis will scan to document comment
source_type:
  - .scss

# The directory that aigis will build to
dest: ./docs

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./aigis/aigis_assets

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./aigis/template_hbs
template_engine: hbs

output_collection:
  - elements
  - generic
  - settings
  - tags
  - tools

component_dir: ./

timestamp_format: 'HH:mm, DD-MM-YYYY'
